<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title><?= tank_engine::get_title(); ?></title>
    <?php  tank_engine::render_rescources(); ?>
  </head>
  <body>
    <!-- this layout (in this case, only standard HTML) is generated by /framework/views/layout.php. -->
    <?php tank_engine::render_errors(); ?>
    <?php $this->render("page"); ?>
  </body>
</html>
